marker-name: QuickShop
lang:
  preview: "{0} - {1} - {2}"
  description: "Item: {0}<br />Owner: {1}<br />Type: {2}<br /> {3} Price: {4}<br />---------------<br />X: {5}<br />Y: {6}<br />Z: {7}<br />"
  spacedesc: "Remaining Space: {0}<br />"
  stockdesc: "Remaining Stock: {0}<br />"
  selling: "Selling"
  buying: "Buying"